### ISSUE TITLE
关于站内搜索

### ISSUE THREAD

**Issue by MAGI003769** [fi3ework/hexo-theme-archer#110]
您好，感谢您持续添加新功能。在更新了主题之后，站内搜索出现了一点问题。按照[说明](https://github.com/fi3ework/hexo-theme-archer/wiki/%E5%90%AF%E7%94%A8-Algolia-%E6%90%9C%E7%B4%A2)里的步骤，都已经执行过了，也没有报错的情况。但是点击搜索的图标始终没有反应。另外，似乎fancy box的功能似乎消失了？

**Comment by fi3ework** [comment]
你好，你的 hexo 的 config 里的 label 是按照 wiki 里写的吧，wiki 里我写错了，包含了一个单引号，把 `didn't` 改为 `did not` 再试一下是否可以呢？
```yaml
 hits_empty: "We did not find any results for the search: ${query}"
```
目前有个小 bug 还不支持单引号..

**Comment by MAGI003769** [comment]
哇，秒回，辛苦了辛苦了。站内搜索解决了， 可以说是很稳。

另外就是fancy box，现在似乎又变成了直接访问目录下的图片。刚刚发现新加入的字数统计和阅读时间，如果enable了会报错，无法渲染,，下面是截取的一部分报错信息，有一段`wordcount is not defined`。
```bash
$ hexo g
INFO  Start processing
INFO  Files loaded in 633 ms
Unhandled rejection ReferenceError: E:\GitHub\Hexo\magi003769.github.io\themes\archer\layout\layout.ejs:15
    13|     <%- partial('_partial/base-header') %>
    14|     <div class="wrapper">
 >> 15|         <%- partial('_partial/base-background-image') %>
    16|         <%- partial('_partial/script/font-loader') %>
    17|         <img class="loading" src="<%- url_for('assets/loading.svg') %>" style="display: block; margin: 6rem auto 0 auto; width: 6rem; height: 6rem;" />
    18|         <div class="container container-unloaded">

E:\GitHub\Hexo\magi003769.github.io\themes\archer\layout\_partial\base-background-image.ejs:65
    63|                 <% if(theme.reading_info) { %>
    64|                     <div class="post-intro-read">
 >> 65|                         <span>Word count: <span class="post-count"><%= wordcount(page.content) %></span> / Reading time: <span class="post-count"><%= min2read(page.content) %> min</span></span>
    66|                     </div>
    67|                 <% } %>
    68|                 <div class="post-intro-meta">

wordcount is not defined
    at eval (eval at <anonymous> (E:\GitHub\Hexo\magi003769.github.io\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:32:342)
    at eval (eval at <anonymous> (E:\GitHub\Hexo\magi003769.github.io\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:32:2181)
    at E:\GitHub\Hexo\magi003769.github.io\node_modules\ejs\lib\ejs.js:255:15
    at Object.exports.render (E:\GitHub\Hexo\magi003769.github.io\node_modules\ejs\lib\ejs.js:293:13)
    at Hexo.ejsRenderer (E:\GitHub\Hexo\magi003769.github.io\node_modules\hexo-renderer-ejs\lib\renderer.js:7:14)

```

**Comment by fi3ework** [comment]
1. 看了下你博客，搜索是可以了，但是搜出来的结果点进去的链接似乎不对...，试一下再重新执行一下  `hexo algolia`
2. fancybox 挂了，可能是加 algolia 的时候不小心弄坏了，晚一点修复好。
3. 字数要装一个 hexo 插件，只写在了安装说明里，所以老用户看不到，新加了个 wiki，见 [我](https://github.com/fi3ework/hexo-theme-archer/wiki/%E5%90%AF%E7%94%A8%E5%AD%97%E6%95%B0%E7%BB%9F%E8%AE%A1%E5%8F%8A%E9%98%85%E8%AF%BB%E6%97%B6%E9%97%B4)

**Comment by fi3ework** [comment]
fancybox bug has been fixed
