### ISSUE TITLE
安装algolia搜索之后，生成静态页面报错是怎么回事哦？

### ISSUE THREAD

**Issue by yuzh233** [fi3ework/hexo-theme-archer#132]
yu_zh@YU-ZH MINGW64 /d/Program Files/Hexo
$ hexo g
FATAL bad indentation of a mapping entry at line 104, column 2:
     algolia:
     ^
YAMLException: bad indentation of a mapping entry at line 104, column 2:
     algolia:
     ^
    at generateError (D:\Program Files\Hexo\node_modules\js-yaml\lib\js-yaml\loa                                   der.js:165:10)
    at throwError (D:\Program Files\Hexo\node_modules\js-yaml\lib\js-yaml\loader                                   .js:171:9)
    at readBlockMapping (D:\Program Files\Hexo\node_modules\js-yaml\lib\js-yaml\                                   loader.js:1080:7)
    at composeNode (D:\Program Files\Hexo\node_modules\js-yaml\lib\js-yaml\loade                                   r.js:1332:12)
    at readDocument (D:\Program Files\Hexo\node_modules\js-yaml\lib\js-yaml\load                                   er.js:1492:3)
    at loadDocuments (D:\Program Files\Hexo\node_modules\js-yaml\lib\js-yaml\loa                                   der.js:1548:5)
    at Object.load (D:\Program Files\Hexo\node_modules\js-yaml\lib\js-yaml\loade                                   r.js:1569:19)
    at Hexo.yamlHelper (D:\Program Files\Hexo\node_modules\hexo\lib\plugins\rend                                   erer\yaml.js:7:15)
    at Hexo.tryCatcher (D:\Program Files\Hexo\node_modules\bluebird\js\release\u                                   til.js:16:23)
    at Hexo.<anonymous> (D:\Program Files\Hexo\node_modules\bluebird\js\release\                                   method.js:15:34)
    at Promise.then.text (D:\Program Files\Hexo\node_modules\hexo\lib\hexo\rende                                   r.js:61:21)
    at tryCatcher (D:\Program Files\Hexo\node_modules\bluebird\js\release\util.j                                   s:16:23)
    at Promise._settlePromiseFromHandler (D:\Program Files\Hexo\node_modules\blu                                   ebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Program Files\Hexo\node_modules\bluebird\js\re                                   lease\promise.js:569:18)
    at Promise._settlePromise0 (D:\Program Files\Hexo\node_modules\bluebird\js\r                                   elease\promise.js:614:10)
    at Promise._settlePromises (D:\Program Files\Hexo\node_modules\bluebird\js\r                                   elease\promise.js:693:18)
    at Async._drainQueue (D:\Program Files\Hexo\node_modules\bluebird\js\release                                   \async.js:133:16)
    at Async._drainQueues (D:\Program Files\Hexo\node_modules\bluebird\js\releas                                   e\async.js:143:10)
    at Immediate.Async.drainQueues (D:\Program Files\Hexo\node_modules\bluebird\                                   js\release\async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by fi3ework** [comment]
确认下 yaml 的格式有没有写错

**Comment by yuzh233** [comment]
可以了，谢谢你拉！
原因是hexo根目录下的 yam 中 "algolia:" 字符串前面多加了一个空格。。😅
