### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by gaofeng-lin** [fi3ework/hexo-theme-archer#329]
![image](https://user-images.githubusercontent.com/66858159/149516276-3805062a-a39b-46c5-982f-1eeb2a9ae08f.png)
我是用本地浏览，但是一直没出结果，发现出错了。
``ERROR {
  err: ReferenceError: C:\Blog\themes\archer\layout\layout.ejs:26
      24|         
      25|         <div class="wrapper">
   >> 26|             <%- partial('_partial/base-background-image') %>
      27|             <%- partial('_partial/script/font-loader') %>
      28|             <img class="loading" src="<%- url_for('assets/loading.svg') %>" style="display: block; margin: 6rem auto 0 auto; width: 6rem; height: 6rem;" />
      29|             <div class="container container-unloaded">

  C:\Blog\themes\archer\layout\_partial\base-background-image.ejs:63
      61|                 <% if(theme.reading_info) { %>
      62|                     <div class="post-intro-read">
   >> 63|                         <span><%- __('word_count') %>: <span class="post-count word-count"><%= wordcount(page.content) %></span><%= __('reading_time') %>: <span class="post-count reading-time"><%= min2read(page.content) %> min</span></span>
      64|                     </div>
      65|                 <% } %>
      66|                 <div class="post-intro-meta">

  wordcount is not defined
      at eval ("C:\\Blog\\themes\\archer\\layout\\_partial\\base-background-image.ejs":127:7)
      at base-background-image (C:\Blog\node_modules\ejs\lib\ejs.js:692:17)
      at _View._compiledSync (C:\Blog\node_modules\hexo\lib\theme\view.js:132:24)
      at _View.renderSync (C:\Blog\node_modules\hexo\lib\theme\view.js:59:25)
      at Object.partial (C:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
      at eval ("C:\\Blog\\themes\\archer\\layout\\layout.ejs":42:17)
      at layout (C:\Blog\node_modules\ejs\lib\ejs.js:692:17)
      at _View._compiled (C:\Blog\node_modules\hexo\lib\theme\view.js:136:50)
      at _View.render (C:\Blog\node_modules\hexo\lib\theme\view.js:39:17)
      at C:\Blog\node_modules\hexo\lib\theme\view.js:51:25
      at tryCatcher (C:\Blog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\Blog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\Blog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\Blog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\Blog\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (C:\Blog\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (C:\Blog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (C:\Blog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (C:\Blog\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (node:internal/timers:464:21) {
    path: 'C:\\Blog\\themes\\archer\\layout\\layout.ejs'
  }
} Render HTML failed: 2022/01/08/hello-world/index.html
Unhandled rejection ReferenceError: C:\Blog\themes\archer\layout\layout.ejs:26
    24|         
    25|         <div class="wrapper">
 >> 26|             <%- partial('_partial/base-background-image') %>
    27|             <%- partial('_partial/script/font-loader') %>
    28|             <img class="loading" src="<%- url_for('assets/loading.svg') %>" style="display: block; margin: 6rem auto 0 auto; width: 6rem; height: 6rem;" />
    29|             <div class="container container-unloaded">

C:\Blog\themes\archer\layout\_partial\base-background-image.ejs:63
    61|                 <% if(theme.reading_info) { %>
    62|                     <div class="post-intro-read">
 >> 63|                         <span><%- __('word_count') %>: <span class="post-count word-count"><%= wordcount(page.content) %></span><%= __('reading_time') %>: <span class="post-count reading-time"><%= min2read(page.content) %> min</span></span>
    64|                     </div>
    65|                 <% } %>
    66|                 <div class="post-intro-meta">

wordcount is not defined
    at eval ("C:\\Blog\\themes\\archer\\layout\\_partial\\base-background-image.ejs":127:7)
    at base-background-image (C:\Blog\node_modules\ejs\lib\ejs.js:692:17)
    at _View._compiledSync (C:\Blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (C:\Blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (C:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval ("C:\\Blog\\themes\\archer\\layout\\layout.ejs":42:17)
    at layout (C:\Blog\node_modules\ejs\lib\ejs.js:692:17)
    at _View._compiled (C:\Blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (C:\Blog\node_modules\hexo\lib\theme\view.js:39:17)
    at C:\Blog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (C:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (node:internal/timers:464:21)

![image](https://user-images.githubusercontent.com/66858159/149516481-e6514521-e8bb-4e42-9389-fb7b41810756.png)

**Comment by LolipopJ** [comment]
Archer 主题依赖于 hexo-generator-json-content 和 hexo-wordcount 库，需要在 Hexo 根目录下手动安装。

参考 README.md 的[此章节](https://github.com/fi3ework/hexo-theme-archer#%E5%AE%89%E8%A3%85%E4%B8%BB%E9%A2%98%E4%BE%9D%E8%B5%96)。

**Comment by LolipopJ** [comment]
采用 yml 数组的形式，在 Markdown 博客（`source/_posts/you_blog.md`）开头编写即可，例如：

``` md
---
title: 这位客官，要来一张我珍藏许久的图片吗
date: 2022/1/13
updated: 2022/1/14
categories:
  - 后端开发
tags:
  - Telegram
  - Bot
  - Node
  - Koa
---

这里是您的正文内容。
```

结果如下：

![image](https://user-images.githubusercontent.com/42314340/149531893-220292ba-5d2c-4899-a753-df596b6ca71a.png)

**Comment by gaofeng-lin** [comment]
@LolipopJ 万分感谢您的帮助！我会把自己的笔记逐渐版上去的。
