### ISSUE TITLE
文章列表摘要如何自定义？

### ISSUE THREAD

**Issue by Jiiiiiin** [fi3ework/hexo-theme-archer#36]
```bash
ERROR Script load failed: scripts/main.js
ReferenceError: document is not defined
    at Object.defineProperty.value (/Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:532)
    at t (/Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:172)
    at Object.defineProperty.value (/Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:294)
    at t (/Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:172)
    at /Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:252
    at /Users/jiiiiiin/Documents/Atom/hexo/blog/scripts/main.js:1:257
    at /Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/hexo/lib/hexo/index.js:232:12
    at tryCatcher (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/promise.js:638:18)
    at /Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/jiiiiiin/Documents/Atom/hexo/blog/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
INFO  Copying files from extend dirs...
[master ad79678] Site updated: 2018-01-28 22:05:11
```

执行任何命令都先报这个错，但是还是可以正常执行。请问有遇到过么？

然后我还想问一下如果，文章列表不需要“摘要”能配置之后去掉么？

![](https://ws3.sinaimg.cn/large/006tNc79ly1fnwobwvjudj31cc0scacp.jpg)

或者说能指定摘要内容？

**Comment by fi3ework** [comment]
1. 报错这个没有遇到过，可能是你node或者hexo的版本过低，升级一下吧。
2. 不显示摘要：将layout/index.ejs 中的第14行删掉重新`gulp build`即可
```html
<a class="content-show-full" href = "<%- url_for(_post.path) %>" >
    <div class="abstract-content">
        <!-- <%- _content %> -->
    </div>
</a>
```

**Comment by Jiiiiiin** [comment]
@fi3ework 好的 我试试 谢谢。 😄

**Comment by secsilm** [comment]
@fi3ework 自定义摘要长度在哪呢，但是找不到在哪了 😄

**Comment by fi3ework** [comment]
@secsilm 在这里啊
![image](https://user-images.githubusercontent.com/12322740/37238605-0a46ca1c-2465-11e8-8717-b26c70216988.png)

**Comment by secsilm** [comment]
@fi3ework 好的好的，我就说以前有的，粗心了
